### ISSUE TITLE
Endpoints for SSH

### ISSUE THREAD

**Issue by nelsonw2014** [CloudBench-IDE/cloudbench#2]
Start/Stop session... more needed...?

**Comment by toshipiazza** [comment]
For PreAlpha1, it will be simpler to have a post endpoint that takes a terminal command, runs it and returns the output. Prefer python subprocess module to os.system and temoporary files.

Later we can create a fully fledged terminal emulator, if the need arises.

**Comment by nelsonw2014** [comment]
k, will do bb

**Comment by nelsonw2014** [comment]
Gonna do this tonight
