### ISSUE TITLE
gh-pages

### ISSUE THREAD

**Issue by toshipiazza** [CloudBench-IDE/cloudbench#6]
Make a static website to put on gh-pages

**Comment by nelsonw2014** [comment]
I want us to pursue using Jekyll for static page generation to reduce boilerplate, increase templating, and make modification easy. A guide to using jekyll with github.io is available [Here](https://help.github.com/articles/using-jekyll-with-pages/)

**Comment by Janblair101** [comment]
Starting now.

**Comment by nelsonw2014** [comment]
Good enough
